-- ============================================================
-- FIFA World Cup 2026 - Prediction Platform
-- Supabase Database Migration
-- ============================================================
-- ⚠ 警告：不要全选运行！全选会 DROP TABLE 清空所有数据！
-- 按需选择对应段落运行：
--   第 104-136 行  → 重新定义算分函数 (SECURITY DEFINER)
--   第 155-168 行 → 新建 INSERT 触发器
--   第 375-386 行 → 一次性重算历史积分
-- https://app.supabase.com → 项目 → SQL Editor → 选择性运行

-- ── 清理旧对象（按依赖顺序） ──
drop view if exists public.leaderboard cascade;
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.calculate_prediction_points(bigint) cascade;
drop trigger if exists trg_predictions_updated on public.predictions;
drop trigger if exists trg_matches_updated on public.matches;
drop trigger if exists trg_profiles_updated on public.profiles;
drop function if exists public.update_timestamp() cascade;
drop table if exists public.chat_messages cascade;
drop table if exists public.predictions cascade;
drop table if exists public.matches cascade;
drop table if exists public.profiles cascade;

-- ── Extensions ──
create extension if not exists "pgcrypto";

-- ── Profiles ──
create table public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text not null unique,
  display_name text,
  total_points integer default 0 not null,
  predictions_count integer default 0 not null,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null
);

-- ── Matches (ID = 匹配编号 1-104，手动指定) ──
create table public.matches (
  id          bigint primary key,
  match_date  date not null,
  match_time  text not null,
  home_team   text not null,
  away_team   text not null,
  stage       text not null,
  group_name  text,
  venue       text not null,
  home_score  integer,
  away_score  integer,
  status      text default 'upcoming' not null,
  match_minute integer,
  injury_time integer,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null
);

-- ── Chat Messages ──
create table public.chat_messages (
  id          bigint primary key generated by default as identity,
  match_id    bigint not null,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  username    text not null,
  message     text not null,
  created_at  timestamptz default now() not null
);
create index idx_chat_match on public.chat_messages(match_id);

-- ── Predictions ──
create table public.predictions (
  id          bigint primary key generated by default as identity,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  match_id    bigint not null references public.matches(id) on delete cascade,
  home_score  integer not null,
  away_score  integer not null,
  points      integer default 0 not null,
  created_at  timestamptz default now() not null,
  unique(user_id, match_id)
);

-- ── Indexes ──
create index idx_predictions_user    on public.predictions(user_id);
create index idx_predictions_match   on public.predictions(match_id);
create index idx_predictions_points  on public.predictions(points desc);
create index idx_matches_status      on public.matches(status);
create index idx_matches_date        on public.matches(match_date);
create index idx_profiles_points     on public.profiles(total_points desc);

-- ── Auto-update updated_at ──
create or replace function public.update_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

create trigger trg_profiles_updated
  before update on public.profiles
  for each row execute function public.update_timestamp();

create trigger trg_matches_updated
  before update on public.matches
  for each row execute function public.update_timestamp();

-- ── Score Calculation Function ──
create or replace function public.calculate_prediction_points(p_match_id bigint)
returns void as $$
declare
  m public.matches;
  pred record;
  earned integer;
begin
  select * into m from public.matches where id = p_match_id;
  if m is null or m.home_score is null or m.away_score is null then
    return;
  end if;

  for pred in
    select * from public.predictions where match_id = p_match_id
  loop
    earned := 0;
    if pred.home_score = m.home_score and pred.away_score = m.away_score then
      earned := 3;
    elsif sign(pred.home_score - pred.away_score) = sign(m.home_score - m.away_score) then
      earned := 1;
    elsif pred.home_score = pred.away_score and m.home_score = m.away_score then
      earned := 1;
    end if;

    update public.predictions set points = earned where id = pred.id;

    update public.profiles
    set total_points = (select coalesce(sum(points), 0) from public.predictions where user_id = pred.user_id),
        predictions_count = (select count(*) from public.predictions where user_id = pred.user_id)
    where id = pred.user_id;
  end loop;
end;
$$ language plpgsql security definer;

-- ── Auto-settlement trigger: when match finishes, calculate points ──
create or replace function public.auto_settle()
returns trigger as $$
begin
  if new.status = 'finished' and (old.status is null or old.status <> 'finished') then
    perform public.calculate_prediction_points(new.id);
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_auto_settle on public.matches;
create trigger trg_auto_settle
  after update on public.matches
  for each row execute function public.auto_settle();

-- ── Auto-settle on INSERT (for seed data with finished status) ──
create or replace function public.auto_settle_insert()
returns trigger as $$
begin
  if new.status = 'finished' then
    perform public.calculate_prediction_points(new.id);
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_auto_settle_insert on public.matches;
create trigger trg_auto_settle_insert
  after insert on public.matches
  for each row execute function public.auto_settle_insert();

-- ── Leaderboard View ──
create or replace view public.leaderboard as
select
  row_number() over (order by total_points desc, username asc) as rank,
  id as user_id,
  username,
  total_points as points,
  predictions_count
from public.profiles
order by total_points desc, username asc;

-- ── Row Level Security (RLS) ──
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.chat_messages enable row level security;

-- Profiles
create policy "Profiles are viewable by everyone" on public.profiles for select using (true);
create policy "Users can update own profile"     on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile"     on public.profiles for insert with check (auth.uid() = id);

-- Matches
create policy "Matches are viewable by everyone"    on public.matches for select using (true);
create policy "Anyone can insert matches"           on public.matches for insert with check (true);
create policy "Anyone can update matches"           on public.matches for update using (true);

-- Predictions
create policy "Users view own predictions"    on public.predictions for select using (auth.uid() = user_id);
create policy "Users insert own predictions"  on public.predictions for insert with check (auth.uid() = user_id);
create policy "Users update own predictions"  on public.predictions for update using (auth.uid() = user_id);
create policy "Users delete own predictions"  on public.predictions for delete using (auth.uid() = user_id);

-- Chat
create policy "Chat viewable by everyone"      on public.chat_messages for select using (true);
create policy "Users insert chat"             on public.chat_messages for insert with check (auth.uid() = user_id);

-- ── Auto-create profile on signup ──
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substring(new.id::text, 1, 8)),
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substring(new.id::text, 1, 8))
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Seed 104 Matches (北京时间 UTC+8) ──
insert into public.matches (id, match_date, match_time, home_team, away_team, stage, group_name, venue, home_score, away_score, status, match_minute, injury_time) values
(1,'2026-06-12','03:00','墨西哥','南非','group','A','阿兹特克体育场·墨西哥城',2,0,'finished',null,0),
(2,'2026-06-12','10:00','韩国','捷克','group','A','阿克伦体育场·瓜达拉哈拉',2,1,'finished',90,7)
on conflict (id) do update set
  home_score = excluded.home_score,
  away_score = excluded.away_score,
  status = case when public.matches.status in ('live','halftime','finished') then public.matches.status else excluded.status end,
  match_minute = coalesce(public.matches.match_minute, excluded.match_minute),
  injury_time = coalesce(public.matches.injury_time, excluded.injury_time);

insert into public.matches (id, match_date, match_time, home_team, away_team, stage, group_name, venue) values
(3,'2026-06-13','03:00','加拿大','波黑','group','B','BMO球场·多伦多'),
(4,'2026-06-13','09:00','美国','巴拉圭','group','D','SoFi体育场·洛杉矶'),
(5,'2026-06-14','03:00','卡塔尔','瑞士','group','B','BMO球场·多伦多'),
(6,'2026-06-14','06:00','巴西','摩洛哥','group','C','利维体育场·旧金山湾区'),
(7,'2026-06-14','09:00','海地','苏格兰','group','C','大都会人寿体育场·纽约/新泽西'),
(8,'2026-06-14','12:00','澳大利亚','土耳其','group','D','SoFi体育场·洛杉矶'),
(9,'2026-06-15','01:00','德国','库拉索','group','E','吉列体育场·波士顿'),
(10,'2026-06-15','04:00','荷兰','日本','group','F','BC广场·温哥华'),
(11,'2026-06-15','07:00','科特迪瓦','厄瓜多尔','group','E','NRG体育场·休斯敦'),
(12,'2026-06-15','10:00','瑞典','突尼斯','group','F','AT&T体育场·达拉斯'),
(13,'2026-06-16','00:00','西班牙','佛得角','group','H','林肯金融球场·费城'),
(14,'2026-06-16','03:00','比利时','埃及','group','G','BBVA体育场·蒙特雷'),
(15,'2026-06-16','06:00','沙特','乌拉圭','group','H','梅赛德斯-奔驰体育场·亚特兰大'),
(16,'2026-06-16','09:00','伊朗','新西兰','group','G','流明球场·西雅图'),
(17,'2026-06-17','03:00','法国','塞内加尔','group','I','利维体育场·旧金山湾区'),
(18,'2026-06-17','06:00','伊拉克','挪威','group','I','大都会人寿体育场·纽约/新泽西'),
(19,'2026-06-17','09:00','阿根廷','阿尔及利亚','group','J','硬石体育场·迈阿密'),
(20,'2026-06-17','12:00','奥地利','约旦','group','J','BMO球场·多伦多'),
(21,'2026-06-18','01:00','葡萄牙','刚果(金)','group','K','吉列体育场·波士顿'),
(22,'2026-06-18','04:00','英格兰','克罗地亚','group','L','BC广场·温哥华'),
(23,'2026-06-18','07:00','加纳','巴拿马','group','L','箭头体育场·堪萨斯城'),
(24,'2026-06-18','10:00','乌兹别克斯坦','哥伦比亚','group','K','AT&T体育场·达拉斯'),
(25,'2026-06-19','00:00','捷克','南非','group','A','阿克伦体育场·瓜达拉哈拉'),
(26,'2026-06-19','03:00','瑞士','波黑','group','B','NRG体育场·休斯敦'),
(27,'2026-06-19','06:00','加拿大','卡塔尔','group','B','流明球场·西雅图'),
(28,'2026-06-19','09:00','墨西哥','韩国','group','A','阿兹特克体育场·墨西哥城'),
(29,'2026-06-20','03:00','美国','澳大利亚','group','D','林肯金融球场·费城'),
(30,'2026-06-20','06:00','苏格兰','摩洛哥','group','C','大都会人寿体育场·纽约/新泽西'),
(31,'2026-06-20','09:00','巴西','海地','group','C','梅赛德斯-奔驰体育场·亚特兰大'),
(32,'2026-06-20','12:00','土耳其','巴拉圭','group','D','BMO球场·多伦多'),
(33,'2026-06-21','01:00','荷兰','瑞典','group','F','吉列体育场·波士顿'),
(34,'2026-06-21','04:00','德国','科特迪瓦','group','E','箭头体育场·堪萨斯城'),
(35,'2026-06-21','08:00','厄瓜多尔','库拉索','group','E','硬石体育场·迈阿密'),
(36,'2026-06-21','12:00','突尼斯','日本','group','F','SoFi体育场·洛杉矶'),
(37,'2026-06-22','00:00','西班牙','沙特','group','H','林肯金融球场·费城'),
(38,'2026-06-22','03:00','比利时','伊朗','group','G','BBVA体育场·蒙特雷'),
(39,'2026-06-22','06:00','乌拉圭','佛得角','group','H','梅赛德斯-奔驰体育场·亚特兰大'),
(40,'2026-06-22','09:00','新西兰','埃及','group','G','流明球场·西雅图'),
(41,'2026-06-23','01:00','阿根廷','奥地利','group','J','吉列体育场·波士顿'),
(42,'2026-06-23','05:00','法国','伊拉克','group','I','梅赛德斯-奔驰体育场·亚特兰大'),
(43,'2026-06-23','08:00','挪威','塞内加尔','group','I','利维体育场·旧金山湾区'),
(44,'2026-06-23','11:00','约旦','阿尔及利亚','group','J','BMO球场·多伦多'),
(45,'2026-06-24','01:00','葡萄牙','乌兹别克斯坦','group','K','吉列体育场·波士顿'),
(46,'2026-06-24','04:00','英格兰','加纳','group','L','大都会人寿体育场·纽约/新泽西'),
(47,'2026-06-24','07:00','巴拿马','克罗地亚','group','L','箭头体育场·堪萨斯城'),
(48,'2026-06-24','10:00','哥伦比亚','刚果(金)','group','K','AT&T体育场·达拉斯'),
(49,'2026-06-25','03:00','瑞士','加拿大','group','B','流明球场·西雅图'),
(50,'2026-06-25','03:00','波黑','卡塔尔','group','B','林肯金融球场·费城'),
(51,'2026-06-25','06:00','苏格兰','巴西','group','C','梅赛德斯-奔驰体育场·亚特兰大'),
(52,'2026-06-25','06:00','摩洛哥','海地','group','C','SoFi体育场·洛杉矶'),
(53,'2026-06-25','09:00','捷克','墨西哥','group','A','AT&T体育场·达拉斯'),
(54,'2026-06-25','09:00','南非','韩国','group','A','NRG体育场·休斯敦'),
(55,'2026-06-26','04:00','库拉索','科特迪瓦','group','E','梅赛德斯-奔驰体育场·亚特兰大'),
(56,'2026-06-26','04:00','厄瓜多尔','德国','group','E','利维体育场·旧金山湾区'),
(57,'2026-06-26','07:00','日本','瑞典','group','F','BC广场·温哥华'),
(58,'2026-06-26','07:00','突尼斯','荷兰','group','F','硬石体育场·迈阿密'),
(59,'2026-06-26','10:00','土耳其','美国','group','D','大都会人寿体育场·纽约/新泽西'),
(60,'2026-06-26','10:00','巴拉圭','澳大利亚','group','D','BMO球场·多伦多'),
(61,'2026-06-27','03:00','挪威','法国','group','I','利维体育场·旧金山湾区'),
(62,'2026-06-27','03:00','塞内加尔','伊拉克','group','I','箭头体育场·堪萨斯城'),
(63,'2026-06-27','08:00','佛得角','沙特','group','H','吉列体育场·波士顿'),
(64,'2026-06-27','08:00','乌拉圭','西班牙','group','H','阿兹特克体育场·墨西哥城'),
(65,'2026-06-27','11:00','埃及','伊朗','group','G','林肯金融球场·费城'),
(66,'2026-06-27','11:00','新西兰','比利时','group','G','流明球场·西雅图'),
(67,'2026-06-28','05:00','巴拿马','英格兰','group','L','BC广场·温哥华'),
(68,'2026-06-28','05:00','克罗地亚','加纳','group','L','大都会人寿体育场·纽约/新泽西'),
(69,'2026-06-28','07:30','哥伦比亚','葡萄牙','group','K','梅赛德斯-奔驰体育场·亚特兰大'),
(70,'2026-06-28','07:30','刚果(金)','乌兹别克斯坦','group','K','SoFi体育场·洛杉矶'),
(71,'2026-06-28','10:00','阿尔及利亚','奥地利','group','J','硬石体育场·迈阿密'),
(72,'2026-06-28','10:00','约旦','阿根廷','group','J','AT&T体育场·达拉斯'),
(73,'2026-06-29','01:00','A组第一','B组第二','r32',null,'阿兹特克体育场·墨西哥城'),
(74,'2026-06-29','01:00','A组第二','C组第三*','r32',null,'BMO球场·多伦多'),
(75,'2026-06-29','05:00','C组第一','D组第二','r32',null,'利维体育场·旧金山湾区'),
(76,'2026-06-29','09:00','E组第一','F组第二','r32',null,'NRG体育场·休斯敦'),
(77,'2026-06-30','01:00','B组第一','A组第二','r32',null,'BMO球场·多伦多'),
(78,'2026-06-30','05:00','D组第一','C组第二','r32',null,'SoFi体育场·洛杉矶'),
(79,'2026-06-30','05:00','D组第二','E组第三*','r32',null,'箭头体育场·堪萨斯城'),
(80,'2026-06-30','09:00','F组第一','E组第二','r32',null,'大都会人寿体育场·纽约/新泽西'),
(81,'2026-07-01','01:00','G组第一','H组第二','r32',null,'流明球场·西雅图'),
(82,'2026-07-01','05:00','G组第二','I组第三*','r32',null,'硬石体育场·迈阿密'),
(83,'2026-07-01','05:00','I组第一','J组第二','r32',null,'SoFi体育场·洛杉矶'),
(84,'2026-07-01','09:00','K组第一','L组第二','r32',null,'吉列体育场·波士顿'),
(85,'2026-07-02','01:00','H组第一','G组第二','r32',null,'林肯金融球场·费城'),
(86,'2026-07-02','05:00','J组第一','I组第二','r32',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(87,'2026-07-02','05:00','K组第二','B组第三*','r32',null,'BBVA体育场·蒙特雷'),
(88,'2026-07-02','09:00','L组第一','K组第二','r32',null,'AT&T体育场·达拉斯'),
(89,'2026-07-05','05:00','W75胜者','W77胜者','r16',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(90,'2026-07-05','09:00','W73胜者','W74胜者','r16',null,'利维体育场·旧金山湾区'),
(91,'2026-07-06','05:00','W76胜者','W78胜者','r16',null,'吉列体育场·波士顿'),
(92,'2026-07-06','09:00','W79胜者','W80胜者','r16',null,'大都会人寿体育场·纽约/新泽西'),
(93,'2026-07-07','05:00','W83胜者','W81胜者','r16',null,'NRG体育场·休斯敦'),
(94,'2026-07-07','09:00','W82胜者','W85胜者','r16',null,'阿兹特克体育场·墨西哥城'),
(95,'2026-07-08','05:00','W84胜者','W87胜者','r16',null,'流明球场·西雅图'),
(96,'2026-07-08','09:00','W86胜者','W88胜者','r16',null,'SoFi体育场·洛杉矶'),
(97,'2026-07-10','05:00','W89胜者','W90胜者','qf',null,'大都会人寿体育场·纽约/新泽西'),
(98,'2026-07-11','06:00','W91胜者','W92胜者','qf',null,'NRG体育场·休斯敦'),
(99,'2026-07-11','09:00','W93胜者','W94胜者','qf',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(100,'2026-07-12','09:00','W95胜者','W96胜者','qf',null,'BMO球场·多伦多'),
(101,'2026-07-15','09:00','WQF1胜者','WQF2胜者','sf',null,'BC广场·温哥华'),
(102,'2026-07-16','09:00','WQF3胜者','WQF4胜者','sf',null,'SoFi体育场·洛杉矶'),
(103,'2026-07-19','05:00','半决赛负者1','半决赛负者2','3rd',null,'硬石体育场·迈阿密'),
(104,'2026-07-20','03:00','半决赛胜者1','半决赛胜者2','final',null,'阿兹特克体育场·墨西哥城')
on conflict (id) do update set
  match_date = excluded.match_date,
  match_time = excluded.match_time,
  home_team = excluded.home_team,
  away_team = excluded.away_team,
  stage = excluded.stage,
  group_name = excluded.group_name,
  venue = excluded.venue;

-- ── Realtime: ensure tables are in the publication ──
-- (If realtime is already enabled in Dashboard, these are no-ops)
do $$
begin
  alter publication supabase_realtime add table public.matches;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.predictions;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null;
end $$;

-- ── v6.5: Add live match tracking columns (run on existing databases) ──
alter table public.matches add column if not exists match_minute integer;
alter table public.matches add column if not exists injury_time integer;

-- ── One-time recalculation: score all finished matches ──
-- (Retroactively fixes matches that were INSERTed as finished before the INSERT trigger existed)
do $$
declare
  mid bigint;
begin
  for mid in select id from public.matches where status = 'finished' and home_score is not null
  loop
    perform public.calculate_prediction_points(mid);
  end loop;
end $$;
