-- ============================================================
-- FIFA World Cup 2026 - Prediction Platform
-- Supabase Database Migration
-- ============================================================
-- Run this in Supabase SQL Editor:
-- https://app.supabase.com → Your Project → SQL Editor → New Query
-- Paste and run.

-- ── Extensions ──
create extension if not exists "pgcrypto";

-- ── Profiles (extends auth.users) ──
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  username    text not null unique,
  display_name text,
  total_points integer default 0 not null,
  predictions_count integer default 0 not null,
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null
);

-- ── Matches ──
create table if not exists public.matches (
  id          bigint primary key generated by default as identity,
  match_date  date not null,
  match_time  text not null,               -- e.g. '16:00'
  home_team   text not null,
  away_team   text not null,
  stage       text not null,               -- 'group','r32','r16','qf','sf','3rd','final'
  group_name  text,                        -- 'A'..'L' for group stage
  venue       text not null,
  home_score  integer,                     -- null until match is played
  away_score  integer,                     -- null until match is played
  status      text default 'upcoming' not null, -- 'upcoming','live','finished'
  created_at  timestamptz default now() not null,
  updated_at  timestamptz default now() not null
);

-- ── Chat Messages ──
create table if not exists public.chat_messages (
  id          bigint primary key generated by default as identity,
  match_id    bigint not null,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  username    text not null,
  message     text not null,
  created_at  timestamptz default now() not null
);
create index if not exists idx_chat_match on public.chat_messages(match_id);
alter table public.chat_messages enable row level security;
create policy "Chat messages viewable by everyone"
  on public.chat_messages for select using (true);
create policy "Users can insert chat messages"
  on public.chat_messages for insert with check (auth.uid() = user_id);

-- ── Predictions ──
create table if not exists public.predictions (
  id          bigint primary key generated by default as identity,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  match_id    bigint not null references public.matches(id) on delete cascade,
  home_score  integer not null,
  away_score  integer not null,
  points      integer default 0 not null,  -- calculated after match
  created_at  timestamptz default now() not null,
  unique(user_id, match_id)               -- one prediction per user per match
);

-- ── Indexes ──
create index if not exists idx_predictions_user    on public.predictions(user_id);
create index if not exists idx_predictions_match   on public.predictions(match_id);
create index if not exists idx_predictions_points  on public.predictions(points desc);
create index if not exists idx_matches_status      on public.matches(status);
create index if not exists idx_matches_date        on public.matches(match_date);
create index if not exists idx_profiles_points     on public.profiles(total_points desc);

-- ── Auto-update updated_at ──
create or replace function public.update_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated
  before update on public.profiles
  for each row execute function public.update_timestamp();

drop trigger if exists trg_matches_updated on public.matches;
create trigger trg_matches_updated
  before update on public.matches
  for each row execute function public.update_timestamp();

-- ── Score Calculation Function ──
-- Called when match scores are updated. Calculates points for all predictions.
create or replace function public.calculate_prediction_points(match_id bigint)
returns void as $$
declare
  m public.matches;
  pred record;
  earned integer;
begin
  select * into m from public.matches where id = match_id;
  if m is null or m.home_score is null or m.away_score is null then
    return;
  end if;

  for pred in
    select * from public.predictions where match_id = match_id
  loop
    earned := 0;

    -- Exact score: 3 points
    if pred.home_score = m.home_score and pred.away_score = m.away_score then
      earned := 3;
    -- Correct result (win/draw/loss): 1 point
    elsif sign(pred.home_score - pred.away_score) = sign(m.home_score - m.away_score) then
      earned := 1;
    -- Both scoreless draw
    elsif pred.home_score = pred.away_score and m.home_score = m.away_score then
      earned := 1;
    end if;

    update public.predictions set points = earned where id = pred.id;

    -- Update user total
    update public.profiles
    set total_points = (
      select coalesce(sum(points), 0) from public.predictions where user_id = pred.user_id
    ),
    predictions_count = (
      select count(*) from public.predictions where user_id = pred.user_id
    )
    where id = pred.user_id;
  end loop;
end;
$$ language plpgsql security definer;

-- ── Leaderboard View ──
create or replace view public.leaderboard as
select
  row_number() over (order by total_points desc, predictions_count desc) as rank,
  id as user_id,
  username,
  total_points as points,
  predictions_count
from public.profiles
where total_points > 0 or predictions_count > 0
order by total_points desc, predictions_count desc;

-- ── Row Level Security (RLS) ──
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

-- Profiles: users can read all, only update their own
create policy "Profiles are viewable by everyone"
  on public.profiles for select using (true);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert with check (auth.uid() = id);

-- Matches: everyone can read, only service_role can modify
create policy "Matches are viewable by everyone"
  on public.matches for select using (true);

create policy "Only service_role can insert matches"
  on public.matches for insert with check (true);

create policy "Only service_role can update matches"
  on public.matches for update using (true);

-- Predictions: users can CRUD their own
create policy "Users can view own predictions"
  on public.predictions for select using (auth.uid() = user_id);

create policy "Users can insert own predictions"
  on public.predictions for insert with check (auth.uid() = user_id);

create policy "Users can update own predictions"
  on public.predictions for update using (auth.uid() = user_id);

create policy "Users can delete own predictions"
  on public.predictions for delete using (auth.uid() = user_id);

-- ── Insert trigger for profiles (auto-create on signup) ──
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substring(new.id::text, 1, 8)),
    coalesce(new.raw_user_meta_data ->> 'username', 'user_' || substring(new.id::text, 1, 8))
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Seed Matches Data (104 matches) ──
-- Run once to populate the matches table.
-- The JS client will also auto-seed on first load, but this ensures data exists.
insert into public.matches (id, match_date, match_time, home_team, away_team, stage, group_name, venue) values
(1,'2026-06-11','15:00','墨西哥','南非','group','A','阿兹特克体育场·墨西哥城'),
(2,'2026-06-11','22:00','韩国','捷克','group','A','阿克伦体育场·瓜达拉哈拉'),
(3,'2026-06-12','15:00','加拿大','波黑','group','B','BMO球场·多伦多'),
(4,'2026-06-12','21:00','美国','巴拉圭','group','D','SoFi体育场·洛杉矶'),
(5,'2026-06-13','15:00','卡塔尔','瑞士','group','B','BMO球场·多伦多'),
(6,'2026-06-13','18:00','巴西','摩洛哥','group','C','利维体育场·旧金山湾区'),
(7,'2026-06-13','21:00','海地','苏格兰','group','C','大都会人寿体育场·纽约/新泽西'),
(8,'2026-06-13','24:00','澳大利亚','土耳其','group','D','SoFi体育场·洛杉矶'),
(9,'2026-06-14','13:00','德国','库拉索','group','E','吉列体育场·波士顿'),
(10,'2026-06-14','16:00','荷兰','日本','group','F','BC广场·温哥华'),
(11,'2026-06-14','19:00','科特迪瓦','厄瓜多尔','group','E','NRG体育场·休斯敦'),
(12,'2026-06-14','22:00','瑞典','突尼斯','group','F','AT&T体育场·达拉斯'),
(13,'2026-06-15','12:00','西班牙','佛得角','group','H','林肯金融球场·费城'),
(14,'2026-06-15','15:00','比利时','埃及','group','G','BBVA体育场·蒙特雷'),
(15,'2026-06-15','18:00','沙特','乌拉圭','group','H','梅赛德斯-奔驰体育场·亚特兰大'),
(16,'2026-06-15','21:00','伊朗','新西兰','group','G','流明球场·西雅图'),
(17,'2026-06-16','15:00','法国','塞内加尔','group','I','利维体育场·旧金山湾区'),
(18,'2026-06-16','18:00','伊拉克','挪威','group','I','大都会人寿体育场·纽约/新泽西'),
(19,'2026-06-16','21:00','阿根廷','阿尔及利亚','group','J','硬石体育场·迈阿密'),
(20,'2026-06-16','24:00','奥地利','约旦','group','J','BMO球场·多伦多'),
(21,'2026-06-17','13:00','葡萄牙','刚果(金)','group','K','吉列体育场·波士顿'),
(22,'2026-06-17','16:00','英格兰','克罗地亚','group','L','BC广场·温哥华'),
(23,'2026-06-17','19:00','加纳','巴拿马','group','L','箭头体育场·堪萨斯城'),
(24,'2026-06-17','22:00','乌兹别克斯坦','哥伦比亚','group','K','AT&T体育场·达拉斯'),
(25,'2026-06-18','12:00','捷克','南非','group','A','阿克伦体育场·瓜达拉哈拉'),
(26,'2026-06-18','15:00','瑞士','波黑','group','B','NRG体育场·休斯敦'),
(27,'2026-06-18','18:00','加拿大','卡塔尔','group','B','流明球场·西雅图'),
(28,'2026-06-18','21:00','墨西哥','韩国','group','A','阿兹特克体育场·墨西哥城'),
(29,'2026-06-19','15:00','美国','澳大利亚','group','D','林肯金融球场·费城'),
(30,'2026-06-19','18:00','苏格兰','摩洛哥','group','C','大都会人寿体育场·纽约/新泽西'),
(31,'2026-06-19','21:00','巴西','海地','group','C','梅赛德斯-奔驰体育场·亚特兰大'),
(32,'2026-06-19','24:00','土耳其','巴拉圭','group','D','BMO球场·多伦多'),
(33,'2026-06-20','13:00','荷兰','瑞典','group','F','吉列体育场·波士顿'),
(34,'2026-06-20','16:00','德国','科特迪瓦','group','E','箭头体育场·堪萨斯城'),
(35,'2026-06-20','20:00','厄瓜多尔','库拉索','group','E','硬石体育场·迈阿密'),
(36,'2026-06-20','24:00','突尼斯','日本','group','F','SoFi体育场·洛杉矶'),
(37,'2026-06-21','12:00','西班牙','沙特','group','H','林肯金融球场·费城'),
(38,'2026-06-21','15:00','比利时','伊朗','group','G','BBVA体育场·蒙特雷'),
(39,'2026-06-21','18:00','乌拉圭','佛得角','group','H','梅赛德斯-奔驰体育场·亚特兰大'),
(40,'2026-06-21','21:00','新西兰','埃及','group','G','流明球场·西雅图'),
(41,'2026-06-22','13:00','阿根廷','奥地利','group','J','吉列体育场·波士顿'),
(42,'2026-06-22','17:00','法国','伊拉克','group','I','梅赛德斯-奔驰体育场·亚特兰大'),
(43,'2026-06-22','20:00','挪威','塞内加尔','group','I','利维体育场·旧金山湾区'),
(44,'2026-06-22','23:00','约旦','阿尔及利亚','group','J','BMO球场·多伦多'),
(45,'2026-06-23','13:00','葡萄牙','乌兹别克斯坦','group','K','吉列体育场·波士顿'),
(46,'2026-06-23','16:00','英格兰','加纳','group','L','大都会人寿体育场·纽约/新泽西'),
(47,'2026-06-23','19:00','巴拿马','克罗地亚','group','L','箭头体育场·堪萨斯城'),
(48,'2026-06-23','22:00','哥伦比亚','刚果(金)','group','K','AT&T体育场·达拉斯'),
(49,'2026-06-24','15:00','瑞士','加拿大','group','B','流明球场·西雅图'),
(50,'2026-06-24','15:00','波黑','卡塔尔','group','B','林肯金融球场·费城'),
(51,'2026-06-24','18:00','苏格兰','巴西','group','C','梅赛德斯-奔驰体育场·亚特兰大'),
(52,'2026-06-24','18:00','摩洛哥','海地','group','C','SoFi体育场·洛杉矶'),
(53,'2026-06-24','21:00','捷克','墨西哥','group','A','AT&T体育场·达拉斯'),
(54,'2026-06-24','21:00','南非','韩国','group','A','NRG体育场·休斯敦'),
(55,'2026-06-25','16:00','库拉索','科特迪瓦','group','E','梅赛德斯-奔驰体育场·亚特兰大'),
(56,'2026-06-25','16:00','厄瓜多尔','德国','group','E','利维体育场·旧金山湾区'),
(57,'2026-06-25','19:00','日本','瑞典','group','F','BC广场·温哥华'),
(58,'2026-06-25','19:00','突尼斯','荷兰','group','F','硬石体育场·迈阿密'),
(59,'2026-06-25','22:00','土耳其','美国','group','D','大都会人寿体育场·纽约/新泽西'),
(60,'2026-06-25','22:00','巴拉圭','澳大利亚','group','D','BMO球场·多伦多'),
(61,'2026-06-26','15:00','挪威','法国','group','I','利维体育场·旧金山湾区'),
(62,'2026-06-26','15:00','塞内加尔','伊拉克','group','I','箭头体育场·堪萨斯城'),
(63,'2026-06-26','20:00','佛得角','沙特','group','H','吉列体育场·波士顿'),
(64,'2026-06-26','20:00','乌拉圭','西班牙','group','H','阿兹特克体育场·墨西哥城'),
(65,'2026-06-26','23:00','埃及','伊朗','group','G','林肯金融球场·费城'),
(66,'2026-06-26','23:00','新西兰','比利时','group','G','流明球场·西雅图'),
(67,'2026-06-27','17:00','巴拿马','英格兰','group','L','BC广场·温哥华'),
(68,'2026-06-27','17:00','克罗地亚','加纳','group','L','大都会人寿体育场·纽约/新泽西'),
(69,'2026-06-27','19:30','哥伦比亚','葡萄牙','group','K','梅赛德斯-奔驰体育场·亚特兰大'),
(70,'2026-06-27','19:30','刚果(金)','乌兹别克斯坦','group','K','SoFi体育场·洛杉矶'),
(71,'2026-06-27','22:00','阿尔及利亚','奥地利','group','J','硬石体育场·迈阿密'),
(72,'2026-06-27','22:00','约旦','阿根廷','group','J','AT&T体育场·达拉斯'),
(73,'2026-06-28','13:00','A组第一','B组第二','r32',null,'阿兹特克体育场·墨西哥城'),
(74,'2026-06-28','13:00','A组第二','C组第三*','r32',null,'BMO球场·多伦多'),
(75,'2026-06-28','17:00','C组第一','D组第二','r32',null,'利维体育场·旧金山湾区'),
(76,'2026-06-28','21:00','E组第一','F组第二','r32',null,'NRG体育场·休斯敦'),
(77,'2026-06-29','13:00','B组第一','A组第二','r32',null,'BMO球场·多伦多'),
(78,'2026-06-29','17:00','D组第一','C组第二','r32',null,'SoFi体育场·洛杉矶'),
(79,'2026-06-29','17:00','D组第二','E组第三*','r32',null,'箭头体育场·堪萨斯城'),
(80,'2026-06-29','21:00','F组第一','E组第二','r32',null,'大都会人寿体育场·纽约/新泽西'),
(81,'2026-06-30','13:00','G组第一','H组第二','r32',null,'流明球场·西雅图'),
(82,'2026-06-30','17:00','G组第二','I组第三*','r32',null,'硬石体育场·迈阿密'),
(83,'2026-06-30','17:00','I组第一','J组第二','r32',null,'SoFi体育场·洛杉矶'),
(84,'2026-06-30','21:00','K组第一','L组第二','r32',null,'吉列体育场·波士顿'),
(85,'2026-07-01','13:00','H组第一','G组第二','r32',null,'林肯金融球场·费城'),
(86,'2026-07-01','17:00','J组第一','I组第二','r32',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(87,'2026-07-01','17:00','K组第二','B组第三*','r32',null,'BBVA体育场·蒙特雷'),
(88,'2026-07-01','21:00','L组第一','K组第二','r32',null,'AT&T体育场·达拉斯'),
(89,'2026-07-04','17:00','W75胜者','W77胜者','r16',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(90,'2026-07-04','21:00','W73胜者','W74胜者','r16',null,'利维体育场·旧金山湾区'),
(91,'2026-07-05','17:00','W76胜者','W78胜者','r16',null,'吉列体育场·波士顿'),
(92,'2026-07-05','21:00','W79胜者','W80胜者','r16',null,'大都会人寿体育场·纽约/新泽西'),
(93,'2026-07-06','17:00','W83胜者','W81胜者','r16',null,'NRG体育场·休斯敦'),
(94,'2026-07-06','21:00','W82胜者','W85胜者','r16',null,'阿兹特克体育场·墨西哥城'),
(95,'2026-07-07','17:00','W84胜者','W87胜者','r16',null,'流明球场·西雅图'),
(96,'2026-07-07','21:00','W86胜者','W88胜者','r16',null,'SoFi体育场·洛杉矶'),
(97,'2026-07-09','17:00','W89胜者','W90胜者','qf',null,'大都会人寿体育场·纽约/新泽西'),
(98,'2026-07-10','18:00','W91胜者','W92胜者','qf',null,'NRG体育场·休斯敦'),
(99,'2026-07-10','21:00','W93胜者','W94胜者','qf',null,'梅赛德斯-奔驰体育场·亚特兰大'),
(100,'2026-07-11','21:00','W95胜者','W96胜者','qf',null,'BMO球场·多伦多'),
(101,'2026-07-14','21:00','WQF1胜者','WQF2胜者','sf',null,'BC广场·温哥华'),
(102,'2026-07-15','21:00','WQF3胜者','WQF4胜者','sf',null,'SoFi体育场·洛杉矶'),
(103,'2026-07-18','17:00','半决赛负者1','半决赛负者2','3rd',null,'硬石体育场·迈阿密'),
(104,'2026-07-19','15:00','半决赛胜者1','半决赛胜者2','final',null,'阿兹特克体育场·墨西哥城')
on conflict (id) do nothing;
